### ISSUE TITLE
[Question] How to add my tests to run when goss runs from target machine?

### ISSUE THREAD

**Issue by joaoasrosa** [SimonBaeumer/puppet-goss#1]
Hi,
I'm using your module to start testing the infrastructure when it is configured using Puppet. From what I observed, when the Puppet Agent does the update, it runs the goss tests in the end. The tests are from the file in this repo.

How can I add extra tests, in order to execute my goss validation using the current implementation?

Thanks

**Comment by SimonBaeumer** [comment]
Hey @joaoasrosa,
I am sorry for the late response. I created a fix in #2 and later create a `1.0.2` release.
